typography_spectrum: 0.4586806434769147
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.7393277976018293
  lightness: 0.12309074005702196
  saturation: 0.3407541914133927
  rhythmicContrast: 0.4822727528444058
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.881520147067633
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: home
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 舞踏
    url: 'https://thegrid.ai/butoh/'
    type: external
  - name: about
    id: 57945ce9-c7dc-476b-a853-74432f65ae20
    type: content
  - name: faq
    id: b0a4f2e9-ea5e-4bd0-9df8-aad5829122c3
    type: content
favicon: null
title: Honza Svasek
content: []
description: inviting life to move in ways it has never moved before
purpose: []
